---

- name: Update apt cache.
  apt:
    update_cache: True

- name: Make sure the current version of ‘mysql-server’ is installed.
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - net-tools
    - python3-pip
    - ansible

# Confirms if the public repository was successfully cloned in the specified folder.
- name: Confirming if the Git repository has been succesfully cloned locally
  ansible.builtin.git:
    repo: https://github.com/galaxy3-net/testscripts.git
    dest: /testscripts/
    clone: no
    update: yes